services:
  nebulawebapp:
    image: nebulawebapp
    container_name: nebulawebapp
    build:
      context: .
      dockerfile: NebulaWebApp/Dockerfile
    restart: always
    ports:
      - "5055"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:5055"
      
   